function MiniIcon({kind}:{kind:'document'|'store'|'box'|'check'|'arrow'}){
 const paths={document:'M14 3H5v18h14V8z M14 3v5h5 M8 12h8 M8 16h6',store:'M4 10v11h16V10 M3 10l2-7h14l2 7 M3 10h18 M9 21v-7h6v7',box:'m12 3 9 5-9 5-9-5z M3 8v9l9 5 9-5V8 M12 13v9',check:'m5 12 4 4L19 6',arrow:'M4 12h16 M14 6l6 6-6 6'};
 return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[kind]}/></svg>;
}

export function CaptureVisual(){return <div className="stage-art capture-art"><div className="capture-flow"><div className="scan-area"><span className="scan-corner corner-tl"/><span className="scan-corner corner-tr"/><span className="scan-corner corner-bl"/><span className="scan-corner corner-br"/><div className="paper-invoice"><span className="paper-heading">INVOICE</span><span className="paper-subheading">Sample distributor</span><div className="paper-rule"/><div className="paper-pair"><span>No. INV-1042</span><span>PDF</span></div><div className="paper-lines"><i/><i/><i/></div><div className="paper-items"><span>PRODUCT</span><span>QTY</span><span>COST</span><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="paper-rule"/><span className="paper-total">3 line items</span></div><span className="scan-beam"/></div><div className="capture-transfer"><MiniIcon kind="arrow"/></div><div className="extracted-card"><span className="extracted-heading"><MiniIcon kind="document"/> Captured details</span><dl><div><dt>Invoice number</dt><dd>INV-1042</dd></div><div><dt>Distributor</dt><dd>Sample distributor</dd></div><div><dt>Line items</dt><dd>3 products identified</dd></div></dl><span className="captured-check"><MiniIcon kind="check"/> Ready to review</span></div></div><div className="stage-bottom-label"><span>PHOTO OR PDF</span><span>STRUCTURED INVOICE DATA</span></div><p className="stage-explanation">Capture the details. Keep the original.</p></div>}

const connections=[[0,0],[0,1],[1,0],[1,1],[1,2],[2,1],[2,2]];
export function ConnectVisual(){return <div className="stage-art connect-art"><svg className="partner-network" viewBox="0 0 440 218" role="img" aria-labelledby="network-title network-desc"><title id="network-title">Many-to-many distributor and store connections</title><desc id="network-desc">Three sample distributors connect to three sample stores. Each distributor serves multiple stores, and each store receives from multiple distributors.</desc><text x="14" y="14" className="network-column-label">DISTRIBUTORS</text><text x="308" y="14" className="network-column-label">STORES</text><g className="network-connections">{connections.map(([d,s])=><path key={`${d}-${s}`} data-connection={`${d}-${s}`} className={d===1?'network-line highlighted':'network-line'} d={`M132 ${51+d*62} C203 ${51+d*62},237 ${51+s*62},308 ${51+s*62}`}/>)}</g>{[0,1,2].map(i=><g key={`d${i}`} data-partner="distributor"><rect x="14" y={29+i*62} width="118" height="44" rx="6" className="distributor-node"/><svg x="24" y={41+i*62} width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="m12 3 9 5-9 5-9-5zM3 8v9l9 5 9-5V8M12 13v9"/></svg><text x="51" y={55+i*62} className="network-name">Distributor {String.fromCharCode(65+i)}</text><circle cx="132" cy={51+i*62} r="3" className="network-port"/></g>)}{[0,1,2].map(i=><g key={`s${i}`} data-partner="store"><rect x="308" y={29+i*62} width="118" height="44" rx="6" className="store-node"/><svg x="321" y={41+i*62} width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M4 10v11h16V10M3 10l2-7h14l2 7M3 10h18M9 21v-7h6v7"/></svg><text x="348" y={55+i*62} className="network-name">Store {String.fromCharCode(65+i)}</text><circle cx="308" cy={51+i*62} r="3" className="network-port"/></g>)}</svg><p className="stage-explanation">Multiple suppliers. Multiple stores. Connected records.</p></div>}

export function UpdateVisual(){return <div className="stage-art update-art"><div className="update-list-heading"><span><MiniIcon kind="box"/> Your product list</span><span className="update-approved"><MiniIcon kind="check"/> Changes applied</span></div><table className="update-table"><caption className="sr-only">Illustrative product updates, with purchase costs per case</caption><thead><tr><th>Product</th><th>Purchase cost / case</th><th>Update</th></tr></thead><tbody><tr><td><strong>Sparkling water</strong><small>12 pack</small></td><td><div className="cost-change"><del>$12.00</del><MiniIcon kind="arrow"/><strong>$13.00</strong></div></td><td><span className="change-badge cost-badge">Cost updated</span></td></tr><tr><td><strong>Sea salt chips</strong><small>24 pack</small></td><td><div className="cost-change"><del>$24.00</del><MiniIcon kind="arrow"/><strong>$22.50</strong></div></td><td><span className="change-badge cost-badge">Cost updated</span></td></tr><tr className="new-product-row"><td><strong>Cold brew</strong><small>6 pack</small></td><td><strong className="new-cost">$18.00</strong></td><td><span className="change-badge new-badge">＋ New product</span></td></tr></tbody></table><div className="update-summary"><span>2 cost changes</span><span>1 product added</span></div><p className="stage-explanation">Purchase costs updated. Previous values preserved.</p></div>}
